name: Workflow

on:
  push:
    branches:
       - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/main' && github.event_path == 'IaC/**'

    steps:
      - name: Print Build
        run: echo "Build"

  terraform:
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/main' && github.event_path == 'frontend/**'

    steps:
      - name: Print Terraform
        run: echo "Terraform"

  manual:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Print Manual
        run: echo "Manual"
